SELECT * FROM DB_EXCEL_OG


--------------------- CREACION DE TODAS LAS TABLAS ---------------------------------

CREATE TABLE victima(
id_victima int generated by default as identity not null,
nombre varchar(100),
apellido varchar(100),
direccion varchar(200),
fecha_primera_sospecha timestamp(6),
fecha_confirmacion timestamp(6),
fecha_muerte timestamp(6),
estado_victima varchar(100),
primary key(id_victima)
);



CREATE TABLE asociados(
id_asociado int generated by default as identity not null,
nombre varchar(100),
apellido varchar(100),
primary key(id_asociado)
);

CREATE TABLE contacto_con_asociado(
id_contacto_asociado int generated by default as identity not null,
id_victima int,
id_asociado int,
dt_inicia timestamp(6),
dt_termina timestamp(6),
dt_conocer timestamp(6),
razon varchar(100),
primary key(id_contacto_asociado),
constraint fk_victima foreign key (id_victima) references victima(id_victima),
constraint fk_asociado foreign key (id_asociado) references asociados(id_asociado)
);

CREATE TABLE hospital(
id_hospital int generated by default as identity not null,
nombre varchar(100),
direccion varchar(200),
primary key(id_hospital)
);

CREATE TABLE hospital_utilizado(
id_hosp_u int generated by default as identity not null,
id_hospital int,
id_victima int,
primary key(id_hosp_u),
constraint fk_hospital foreign key (id_hospital) references hospital(id_hospital),
constraint fk_victima_hosp foreign key (id_victima) references victima(id_victima)
);

CREATE TABLE ubicacion(
id_ubicacion int generated by default as identity not null,
direccion varchar(200),
primary key(id_ubicacion)
);

CREATE TABLE ubicaciones_victima(
id_ubicacion_v int generated by default as identity not null,
id_ubicacion int,
id_victima int,
dt_llegada timestamp(6),
dt_salida timestamp(6),
primary key(id_ubicacion_v),
constraint fk_ubicacion foreign key (id_ubicacion) references ubicacion(id_ubicacion),
constraint fk_victima_ubi foreign key (id_victima) references victima(id_victima)
);

CREATE TABLE tratamiento(
id_tratamiento int generated by default as identity not null,
nombre_tratamiento varchar(100),
efectividad_gen int,
primary key(id_tratamiento)
);


CREATE TABLE tratamiento_aplicado(
id_trtmnto_aplicado int generated by default as identity not null,
id_tratamiento int,
id_victima int,
dt_inicio timestamp(6),
dt_final timestamp(6),
efectividad int,
primary key(id_trtmnto_aplicado),
constraint fk_tratamiento foreign key (id_tratamiento) references tratamiento(id_tratamiento),
constraint fk_victima_trt foreign key (id_victima) references victima(id_victima)
);



--------------------- LLENAR TABLAS CON LA INFO DE LA TABLA CARGADA DE MANERA MASIVA ----------------------

------- INGRESAR DATOS A *** VICTIMA *** -----

INSERT INTO victima(nombre, apellido, direccion, fecha_primera_sospecha, fecha_confirmacion, fecha_muerte , estado_victima)
SELECT DISTINCT NOMBRE_VICTIMA, 
APELLIDO_VICTIMA, 
DIRECCION_VICTIMA, 
TO_DATE(FECHA_PRIMERA_SOSPECHA, 'DD/MM/YYYY HH24:MI'), 
TO_DATE(FECHA_CONFIRMACION, 'DD/MM/YYYY HH24:MI'), 
TO_DATE(FECHA_MUERTE, 'DD/MM/YYYY HH24:MI'),
ESTADO_VICTIMA    
FROM DB_EXCEL_OG

SELECT * FROM VICTIMA
ORDER BY ID_VICTIMA ASC

------- INGRESAR DATOS A *** ASOCIADOS *** -----
INSERT INTO asociados(nombre, apellido)
SELECT DISTINCT NOMBRE_ASOCIADO, 
APELLIDO_ASOCIADO  
FROM DB_EXCEL_OG

------- INGRESAR DATOS A *** HOSPITAL *** -----
INSERT INTO hospital(nombre, direccion)
SELECT DISTINCT NOMBRE_HOSPITAL, 
DIRECCION_HOSPITAL 
FROM DB_EXCEL_OG
ORDER BY 1

SELECT * FROM hospital
ORDER BY ID_HOSPITAL ASC


------- INGRESAR DATOS A *** UBICACION *** -----

INSERT INTO ubicacion(direccion)
SELECT DISTINCT UBICACION_VICTIMA 
FROM DB_EXCEL_OG

SELECT * FROM ubicacion
ORDER BY ID_UBICACION ASC


------- INGRESAR DATOS A *** TRATAMIENTO *** -----
INSERT INTO tratamiento(nombre_tratamiento, efectividad_gen)
SELECT DISTINCT TRATAMIENTO, EFECTIVIDAD
FROM DB_EXCEL_OG

SELECT * FROM tratamiento
ORDER BY ID_TRATAMIENTO ASC



------- INGRESAR DATOS A *** CONTACTO_CON_ASOCIADO *** -----
INSERT INTO CONTACTO_CON_ASOCIADO(id_victima, id_asociado, dt_inicia, dt_termina, dt_conocer, razon)
SELECT DISTINCT VIC.ID_VICTIMA, ASO.ID_ASOCIADO, 
TO_DATE(TT.FECHA_INICIO_CONTACTO,'DD/MM/YYYY HH24:MI'), 
TO_DATE(TT.FECHA_FIN_CONTACTO,'DD/MM/YYYY HH24:MI'), 
TO_DATE(TT.FECHA_CONOCIO,'DD/MM/YYYY HH24:MI'), 
TT.CONTACTO_FISICO
FROM DB_EXCEL_OG TT
INNER JOIN VICTIMA vic
	ON TT.NOMBRE_VICTIMA = VIC.NOMBRE AND TT.APELLIDO_VICTIMA = VIC.APELLIDO 
INNER JOIN ASOCIADOS aso
	ON TT.NOMBRE_ASOCIADO = ASO.NOMBRE AND TT.APELLIDO_ASOCIADO = ASO.APELLIDO 
	
SELECT * FROM CONTACTO_CON_ASOCIADO
ORDER BY ID_CONTACTO_ASOCIADO 



------- INGRESAR DATOS A *** HOSPITAL_UTLIZADO *** -----
INSERT INTO HOSPITAL_UTILIZADO (id_hospital, id_victima)
SELECT DISTINCT hosp.ID_HOSPITAL, 
--hosp.NOMBRE, 
vic.ID_VICTIMA
--vic.NOMBRE, vic.APELLIDO  
FROM DB_EXCEL_OG TT
INNER JOIN HOSPITAL hosp
	ON TT.NOMBRE_HOSPITAL = hosp.NOMBRE
INNER JOIN VICTIMA vic
	ON TT.NOMBRE_VICTIMA = vic.NOMBRE AND TT.APELLIDO_VICTIMA = VIC.APELLIDO
	
	
	
SELECT * FROM HOSPITAL_UTILIZADO
ORDER BY ID_HOSP_U  



------- INGRESAR DATOS A *** UBICACIONES_VICTIMA *** -----
INSERT INTO UBICACIONES_VICTIMA(id_ubicacion, id_victima, dt_llegada, dt_salida)
SELECT DISTINCT ubi.ID_UBICACION, v.ID_VICTIMA, 
TO_DATE(TT.FECHA_LLEGADA ,'DD/MM/YYYY HH24:MI'), 
TO_DATE(TT.FECHA_RETIRO ,'DD/MM/YYYY HH24:MI') 
FROM DB_EXCEL_OG TT
INNER JOIN UBICACION ubi
	ON TT.UBICACION_VICTIMA = UBI.DIRECCION
INNER JOIN VICTIMA v
	ON TT.NOMBRE_VICTIMA = v.NOMBRE AND TT.APELLIDO_VICTIMA = V.APELLIDO

SELECT * FROM UBICACIONES_VICTIMA
ORDER BY ID_UBICACION_V  



------- INGRESAR DATOS A *** TRATAMIENTO_APLICADO *** -----
INSERT INTO TRATAMIENTO_APLICADO(id_tratamiento, id_victima, dt_inicio, dt_final, efectividad)
SELECT DISTINCT t.ID_TRATAMIENTO, v.ID_VICTIMA, 
TO_DATE(tt.FECHA_INICIO_TRATAMIENTO,'DD/MM/YYYY HH24:MI'), 
TO_DATE(tt.FECHA_FIN_TRATAMIENTO,'DD/MM/YYYY HH24:MI'), 
tt.EFECTIVIDAD_EN_VICTIMA
FROM DB_EXCEL_OG TT
INNER JOIN TRATAMIENTO t
	ON TT.TRATAMIENTO = t.NOMBRE_TRATAMIENTO
INNER JOIN VICTIMA v 
	ON TT.NOMBRE_VICTIMA = v.NOMBRE AND TT.APELLIDO_VICTIMA = v.APELLIDO 

--WHERE v.nombre = 'Aaron' AND v.apellido = 'Rodriguez'

	
	
SELECT COUNT(ID_VICTIMA)
FROM VICTIMA
WHERE NOMBRE  IS NOT NULL

SELECT COUNT(ID_HOSPITAL)
FROM HOSPITAL
WHERE NOMBRE  IS NOT NULL

SELECT COUNT(ID_UBICACION)
FROM UBICACION
WHERE DIRECCION  IS NOT NULL

SELECT COUNT(ID_TRATAMIENTO)
FROM TRATAMIENTO
WHERE NOMBRE_TRATAMIENTO  IS NOT NULL

SELECT COUNT(ID_ASOCIADO)
FROM ASOCIADOS
WHERE NOMBRE  IS NOT NULL
	

SELECT COUNT(ID_HOSP_U)
FROM HOSPITAL_UTILIZADO

SELECT COUNT(ID_TRTMNTO_APLICADO)
FROM TRATAMIENTO_APLICADO ta

SELECT COUNT(ID_UBICACION_V)
FROM UBICACIONES_VICTIMA uv 

SELECT COUNT(ID_CONTACTO_ASOCIADO)
FROM CONTACTO_CON_ASOCIADO


-----------------------------------------------------------------------------------------------------------
------------------------------------ CONSULTAS DEL ENUNCIADO ----------------------------------------------


--- CONSULTA 1 ---
SELECT DISTINCT h.NOMBRE ,  h.DIRECCION  , COUNT(v.ESTADO_VICTIMA) CANTIDAD_MUERTES 
FROM HOSPITAL_UTILIZADO hu 
INNER JOIN HOSPITAL h
	ON hu.ID_HOSPITAL = h.ID_HOSPITAL
INNER JOIN VICTIMA v 
	ON hu.ID_VICTIMA = v.ID_VICTIMA
WHERE v.ESTADO_VICTIMA = 'Muerte' OR v.FECHA_MUERTE IS NOT NULL
GROUP BY h.NOMBRE, h.DIRECCION
ORDER BY 3 DESC



--- CONSULTA 2 ---
SELECT v.NOMBRE, v.APELLIDO, v.ESTADO_VICTIMA, t.NOMBRE_TRATAMIENTO, ta.EFECTIVIDAD 
FROM VICTIMA v
INNER JOIN TRATAMIENTO_APLICADO ta
	ON V.ID_VICTIMA = ta.ID_VICTIMA
INNER JOIN TRATAMIENTO t
	ON ta.ID_TRATAMIENTO = t.ID_TRATAMIENTO
WHERE t.NOMBRE_TRATAMIENTO = 'Transfusiones de sangre' AND ta.EFECTIVIDAD > 5 AND v.ESTADO_VICTIMA = 'En cuarentena'
ORDER BY 5 DESC



--- CONSULTA 3 ---
SELECT v.NOMBRE, v.APELLIDO, v.DIRECCION, COUNT(DISTINCT CCA.ID_ASOCIADO) as PERS_ASOCIADAS
FROM VICTIMA v 
INNER JOIN CONTACTO_CON_ASOCIADO cca 
	ON v.ID_VICTIMA = CCA.ID_VICTIMA
WHERE v.ESTADO_VICTIMA = 'Muerte' OR FECHA_MUERTE IS NOT NULL
GROUP BY v.NOMBRE, v.APELLIDO, v.DIRECCION
HAVING COUNT(DISTINCT CCA.ID_ASOCIADO) > 3
ORDER BY 4 DESC


--- CONSULTA 4 ---
SELECT v.NOMBRE, v.APELLIDO, COUNT(DISTINCT CCA.ID_ASOCIADO) as PERS_ASOCIADAS
FROM VICTIMA v 
INNER JOIN CONTACTO_CON_ASOCIADO cca 
	ON v.ID_VICTIMA = CCA.ID_VICTIMA
WHERE v.ESTADO_VICTIMA = 'Suspendido' AND CCA.RAZON = 'Beso'
GROUP BY v.NOMBRE, v.APELLIDO, v.DIRECCION
HAVING COUNT(DISTINCT CCA.ID_ASOCIADO) > 2
ORDER BY 3 DESC


--- CONSULTA 5 ---
SELECT v.NOMBRE, v.APELLIDO, COUNT(TA.ID_TRATAMIENTO)
FROM VICTIMA v 
INNER JOIN TRATAMIENTO_APLICADO ta
	ON V.ID_VICTIMA = TA.ID_VICTIMA
INNER JOIN TRATAMIENTO t
	ON t.ID_TRATAMIENTO = TA.ID_TRATAMIENTO 
WHERE T.NOMBRE_TRATAMIENTO = 'Oxigeno'
GROUP BY v.NOMBRE, v.APELLIDO 
ORDER BY 3 DESC
FETCH NEXT 5 ROWS ONLY


--- CONSULTA 6 ---
SELECT v.NOMBRE , v.APELLIDO, v.FECHA_MUERTE, u.DIRECCION, t.NOMBRE_TRATAMIENTO 
FROM VICTIMA v
INNER JOIN TRATAMIENTO_APLICADO ta
	ON V.ID_VICTIMA = TA.ID_VICTIMA
INNER JOIN TRATAMIENTO t
	ON t.ID_TRATAMIENTO = TA.ID_TRATAMIENTO
INNER JOIN UBICACIONES_VICTIMA uv 
	ON v.ID_VICTIMA = uv.ID_VICTIMA
INNER JOIN UBICACION u 
	ON uv.ID_UBICACION = u.ID_UBICACION
WHERE T.NOMBRE_TRATAMIENTO = 'Manejo de la presion arterial' AND u.DIRECCION='1987 Delphine Well' AND v.FECHA_MUERTE IS NOT NULL




--- CONSULTA 7 ---
SELECT v.NOMBRE, v.APELLIDO, v.DIRECCION, COUNT(DISTINCT CCA.ID_ASOCIADO) as PERS_ASOCIADAS,
COUNT (DISTINCT ta.ID_TRATAMIENTO) as CANT_TRTM
FROM VICTIMA v 
INNER JOIN CONTACTO_CON_ASOCIADO cca 
	ON v.ID_VICTIMA = CCA.ID_VICTIMA
INNER JOIN HOSPITAL_UTILIZADO hu 
	ON v.ID_VICTIMA = hu.ID_VICTIMA
INNER JOIN TRATAMIENTO_APLICADO ta
	ON V.ID_VICTIMA = TA.ID_VICTIMA
GROUP BY v.NOMBRE, v.APELLIDO, v.DIRECCION
HAVING COUNT(DISTINCT CCA.ID_ASOCIADO) < 2 AND COUNT (DISTINCT ta.ID_TRATAMIENTO) = 2
ORDER BY 5 DESC


--- CONSULTA 8 ---
SELECT V.NOMBRE, V.APELLIDO, EXTRACT (MONTH FROM V.FECHA_PRIMERA_SOSPECHA) Mes
FROM VICTIMA v 


SELECT nombre, apellido, cant_tratamientos
FROM (
SELECT v.NOMBRE AS nombre, v.APELLIDO AS apellido, COUNT(t.ID_TRATAMIENTO) AS cant_tratamientos
FROM VICTIMA v
INNER JOIN TRATAMIENTO_APLICADO ta 
	ON v.ID_VICTIMA = ta.ID_VICTIMA
INNER JOIN TRATAMIENTO t 
	ON t.ID_TRATAMIENTO = ta.ID_TRATAMIENTO
GROUP BY v.NOMBRE, v.APELLIDO
) tratamientos
WHERE cant_tratamientos = (
SELECT MAX(cant_tratamientos) FROM (
SELECT COUNT(*) AS cant_tratamientos FROM TRATAMIENTO_APLICADO GROUP BY ID_VICTIMA
) tratamientos_por_victima
)
OR cant_tratamientos = (
SELECT MIN(cant_tratamientos) FROM (
SELECT COUNT(*) AS cant_tratamientos FROM TRATAMIENTO_APLICADO GROUP BY ID_VICTIMA
) tratamientos_por_victima
)
ORDER BY 3 DESC

------ FULL -------
SELECT v.NOMBRE AS nombre, v.APELLIDO AS apellido,
EXTRACT(MONTH FROM v.FECHA_PRIMERA_SOSPECHA) AS mes,
COUNT(t.ID_TRATAMIENTO) AS cant_tratamientos
FROM VICTIMA v
INNER JOIN TRATAMIENTO_APLICADO ta ON v.ID_VICTIMA = ta.ID_VICTIMA
INNER JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO = ta.ID_TRATAMIENTO
GROUP BY v.NOMBRE, v.APELLIDO, v.FECHA_PRIMERA_SOSPECHA
HAVING COUNT(t.ID_TRATAMIENTO) = (
SELECT MAX(cant_tratamientos)
FROM (
SELECT COUNT(*) AS cant_tratamientos
FROM TRATAMIENTO_APLICADO
GROUP BY ID_VICTIMA
) tratamientos_por_victima
) OR COUNT(t.ID_TRATAMIENTO) = (
SELECT MIN(cant_tratamientos)
FROM (
SELECT COUNT(*) AS cant_tratamientos
FROM TRATAMIENTO_APLICADO
GROUP BY ID_VICTIMA
) tratamientos_por_victima
)
ORDER BY cant_tratamientos DESC




--- CONSULTA 9 ---

SELECT
h.NOMBRE,
COUNT(hu.ID_VICTIMA) AS VIC_PER_HOSP,
(COUNT(hu.ID_VICTIMA)/366)*100 PORCT_VICTMS
FROM VICTIMA v 
INNER JOIN HOSPITAL_UTILIZADO hu
	ON V.ID_VICTIMA = HU.ID_VICTIMA
INNER JOIN HOSPITAL h 
	ON h.ID_HOSPITAL = hu.ID_HOSPITAL
GROUP BY h.nombre
ORDER BY 1


--- CONSULTA 10 ---

SELECT nombre, razon, CANT_CASOS
FROM (
  SELECT h.NOMBRE AS nombre, cca.RAZON AS razon, COUNT(cca.RAZON) AS CANT_CASOS,
         ROW_NUMBER() OVER (PARTITION BY h.NOMBRE ORDER BY COUNT(cca.RAZON) DESC) AS RN
  FROM VICTIMA v 
  INNER JOIN CONTACTO_CON_ASOCIADO cca 
    ON v.ID_VICTIMA = cca.ID_VICTIMA 
  INNER JOIN HOSPITAL_UTILIZADO hu 
    ON hu.ID_VICTIMA = v.ID_VICTIMA
  INNER JOIN HOSPITAL h 
    ON h.ID_HOSPITAL = hu.ID_HOSPITAL
  WHERE cca.RAZON IS NOT NULL
  GROUP BY h.NOMBRE, cca.RAZON
)
WHERE RN = 1






DROP TABLE contacto_con_asociado;
DROP TABLE hospital_utilizado;
DROP TABLE ubicaciones_victima;
DROP TABLE tratamiento_aplicado;
DROP TABLE asociados;
DROP TABLE hospital;
DROP TABLE ubicacion;
DROP TABLE tratamiento;
DROP TABLE victima;


































